server:
  port: 9001

spring:
  profiles:
    active: development

  logging:
    level:
      org:
        springframework: debug
        hibernate:
          SQL: debug
          type:
            descriptor:
              sql:
                BasicBinder: trace


  h2:
    console:
      enabled: true
      path: /ddoview

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:9092/~/ddoview
      username: sa
      password:
      driver-class-name: org.h2.Driver
      minimumIdle: 10
      maxLifetime: 180000
      connectionTimeout: 30000
      maximum-pool-size: 10
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8

  jpa:
    generate-ddl: true
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.default_batch_fetch_size: 1000
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true
        use_sql_comments: true

springdoc:
  version: '1.0'
  api-docs:
    groups:
      enabled: true
    path: /
  swagger-ui:
    path: /swagger-ui.html
#    display-request-duration: true
#    groups-order: DESC
#    operations-sorter: alpha
#    tags-sorter: alpha
    display-query-params-without-oauth2: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**
    - /test/**

